# -*- coding: utf-8 -*-
"""TTSipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGlY1XTKUJv5D5cVkfRrgcnV0VSCM-6t
"""

# 1. Install system audio dependencies
!sudo apt-get update
!sudo apt-get install -y espeak-ng libsndfile1-dev

# 2. Wipe Colab's default conflicting versions
!pip uninstall -y transformers TTS trainer coqui-tts-trainer

# 3. Install the strict, stable dependency matrix
!pip install transformers==4.29.2
!pip install TTS==0.22.0
!pip install coqui-tts-trainer
!pip install tensorboard

# 1. Install system audio dependencies
!sudo apt-get update
!sudo apt-get install -y espeak-ng libsndfile1-dev

# 2. Install the modern, compatible forks
!pip install coqui-tts coqui-tts-trainer tensorboard

import os
import shutil
import pandas as pd

# 1. Clone your specific branch
!git clone -b Mkuru https://github.com/NjugunaWilfred-01/Sheng-TTS-model.git

# 2. Define all paths
dataset_root = "/content/Sheng-TTS-model/dataset"
segmented_dir = os.path.join(dataset_root, "segmented")
manifest_path = os.path.join(dataset_root, "clean_manifest.csv")

tts_data_dir = "/content/tts_ready_dataset"
wavs_dir = os.path.join(tts_data_dir, "wavs")
output_meta_path = os.path.join(tts_data_dir, "metadata.csv")

os.makedirs(wavs_dir, exist_ok=True)

# 3. Flatten audio files into wavs/
print("Copying audio files...")
for root, dirs, files in os.walk(segmented_dir):
    for file in files:
        if file.endswith(".wav"):
            source = os.path.join(root, file)
            destination = os.path.join(wavs_dir, file)
            if not os.path.exists(destination):
                shutil.copy2(source, destination)

# 4. Generate the LJSpeech metadata.csv
df = pd.read_csv(manifest_path)
audio_col = next((c for c in df.columns if "audio" in c.lower() or "file" in c.lower() or "path" in c.lower()), df.columns[0])
text_col = next((c for c in df.columns if "text" in c.lower() or "transcript" in c.lower()), df.columns[1])

ljspeech_lines = []
for _, row in df.iterrows():
    raw_path = str(row[audio_col])
    filename = os.path.basename(raw_path).replace(".wav", "")
    transcript = str(row[text_col]).strip()
    ljspeech_lines.append(f"{filename}|{transcript}|{transcript}")

with open(output_meta_path, "w", encoding="utf-8") as f:
    for line in ljspeech_lines:
        f.write(line + "\n")

print("Data Prep Complete! Ready for training.")

import re

metadata_path = "/content/tts_ready_dataset/metadata.csv"

# Basic number to Swahili words mapping
num_map = {
    "0": "zero", "1": "jamo", "2": "mbwegze", "3": "tatu", "4": "nne",
    "5": "tano", "6": "sita", "7": "saba", "8": "nane", "9": "tisa",
    "10": "kumi", "11": "kumi na moja", "12": "kumi na mbili",
    "16": "kumi na sita", "20": "mbao", "80": "themanini",
    "100": "soo", "1000": "elfu moja", "16000": "elfu kumi na sita",
}

def replace_numbers(text):
    # Strip commas inside numbers (e.g. 16,000 -> 16000)
    text = re.sub(r'(?<=\d),(?=\d)', '', text)
    # Replace known numbers
    def lookup(match):
        val = match.group(0)
        return num_map.get(val, val)

    # Run lookup
    text = re.sub(r'\b\d+\b', lookup, text)
    # Remove any leftover special characters that aren't basic punctuation
    text = re.sub(r'[%$#@&*\/\\\[\]_+=<>]', ' ', text)
    return re.sub(r'\s+', ' ', text).strip()

# Clean metadata.csv
cleaned_lines = []
with open(metadata_path, "r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split("|")
        if len(parts) >= 2:
            wav_id = parts[0]
            transcript = replace_numbers(parts[1])
            normalized = replace_numbers(parts[-1])
            cleaned_lines.append(f"{wav_id}|{transcript}|{normalized}\n")

with open(metadata_path, "w", encoding="utf-8") as f:
    f.writelines(cleaned_lines)

print(f"Cleaned {len(cleaned_lines)} rows in metadata.csv. Numbers and rogue symbols removed!")

!rm -rf /content/tts_train_dir/*

import os
import torch
import transformers.pytorch_utils

# -------------------------------------------------------------------
# THE FIX: Monkey-patch the missing Hugging Face functions in memory
# -------------------------------------------------------------------
# Coqui TTS looks for functions that Hugging Face recently deleted.
# We map them directly to standard PyTorch functions before Coqui imports.
transformers.pytorch_utils.isin_mps_friendly = torch.isin

import transformers.utils.import_utils
if not hasattr(transformers.utils.import_utils, 'is_torch_greater_or_equal'):
    transformers.utils.import_utils.is_torch_greater_or_equal = lambda *args, **kwargs: True
# -------------------------------------------------------------------

# Now the imports will succeed flawlessly!
from trainer import Trainer, TrainerArgs
from TTS.tts.configs.shared_configs import BaseDatasetConfig
from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.vits import Vits, VitsAudioConfig
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

dataset_path = "/content/tts_ready_dataset"
output_path = "/content/tts_train_dir"

# 1. Configure Dataset
dataset_config = BaseDatasetConfig(
    formatter="ljspeech",
    meta_file_train="metadata.csv",
    path=dataset_path
)

# 2. Configure Audio
audio_config = VitsAudioConfig(
    sample_rate=22050,
    win_length=1024,
    hop_length=256,
    num_mels=80,
    mel_fmin=0,
    mel_fmax=None
)

# 3. Configure Model for Character-based Training
config = VitsConfig(
    audio=audio_config,
    run_name="vits_sheng_character",
    batch_size=16,          # Drop to 8 if you get CUDA memory errors
    eval_batch_size=8,
    batch_group_size=4,
    num_loader_workers=2,
    num_eval_loader_workers=2,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=1000,
    text_cleaner="basic_cleaners",
    use_phonemes=False,     # CRITICAL for Sheng slang
    compute_input_seq_cache=True,
    print_step=25,
    print_eval=True,
    mixed_precision=True,
    output_path=output_path,
    datasets=[dataset_config],
    save_step=1000,
)

# 4. Initialize Components
ap = AudioProcessor.init_from_config(config)
tokenizer, config = TTSTokenizer.init_from_config(config)
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=True,
    eval_split_max_size=config.eval_split_max_size,
    eval_split_size=config.eval_split_size
)

# 5. Initialize and Start Trainer
model = Vits(config, ap, tokenizer, speaker_manager=None)
trainer = Trainer(
    TrainerArgs(),
    config,
    output_path,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples
)

print("Starting VITS fine-tuning...")
trainer.fit()